# /* wallust template - colors-hyprland */ 

$background = rgb(000004)
$foreground = rgb(D9ECF2)
$color0 = rgb(000004)
$color1 = rgb(719CAD)
$color2 = rgb(9C98B6)
$color3 = rgb(9BACC2)
$color4 = rgb(A4AAC6)
$color5 = rgb(89B5CA)
$color6 = rgb(91C9D9)
$color7 = rgb(C0DCE4)
$color8 = rgb(869A9F)
$color9 = rgb(719CAD)
$color10 = rgb(9C98B6)
$color11 = rgb(9BACC2)
$color12 = rgb(A4AAC6)
$color13 = rgb(89B5CA)
$color14 = rgb(91C9D9)
$color15 = rgb(C0DCE4)
