# /* wallust template - colors-hyprland */ 

$background = rgb(121110)
$foreground = rgb(D2CFCF)
$color0 = rgb(3A3938)
$color1 = rgb(3F4755)
$color2 = rgb(474869)
$color3 = rgb(545763)
$color4 = rgb(4C5298)
$color5 = rgb(6B686F)
$color6 = rgb(7E7677)
$color7 = rgb(B6B2B3)
$color8 = rgb(7F7D7D)
$color9 = rgb(3F4755)
$color10 = rgb(474869)
$color11 = rgb(545763)
$color12 = rgb(4C5298)
$color13 = rgb(6B686F)
$color14 = rgb(7E7677)
$color15 = rgb(B6B2B3)
