# Preload images (do this for every image you want to use)
preload = ~/home/shader/.assets/.wallpapers/cold/46.jpg

# Assign wallpaper to the monitor (use the exact name from the log: eDP-1)
wallpaper = eDP-1,~/home/shader/.assets/.wallpapers/cold/46.jpg 
# Alternative: wildcard / default for any monitor
# wallpaper = ,/path/to/your/wallpaper.jpg
